/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexer;

import java.io.*;
import node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleano(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimprograma(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimse(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimavalie(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFaca(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimenquanto(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepita(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDe(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPasso(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAte(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimpara(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdadeiro(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetor(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokenSpecifier(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProductionSpecifier(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorq(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorq(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorigualq(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorigualq(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtrib(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAparentese(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFparentese(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBkt(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBkt(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirg(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoevirg(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoispontos(line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentlinha(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbrebloco(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechabloco(line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new57(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumero(text, line, pos); }
    Token new58(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumInteiro(text, line, pos); }
    Token new59(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumReal(text, line, pos); }
    Token new60(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new61(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {39, 39, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {65, 79, 20}, {80, 80, 21}, {81, 83, 20}, {84, 84, 22}, {85, 90, 20}, {91, 91, 23}, {93, 93, 24}, {95, 95, 25}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 32}, {105, 105, 33}, {106, 107, 32}, {108, 108, 34}, {109, 109, 32}, {110, 110, 35}, {111, 111, 36}, {112, 112, 37}, {113, 113, 32}, {114, 114, 38}, {115, 115, 39}, {116, 117, 32}, {118, 118, 40}, {119, 122, 32}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 41}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 9, 42}, {11, 12, 42}, {14, 38, 42}, {39, 39, 43}, {40, 65535, 42}, },
            {},
            {},
            {{47, 47, 44}, },
            {},
            {},
            {{48, 57, 45}, },
            {},
            {{42, 42, 46}, {47, 47, 47}, },
            {{44, 44, 48}, {48, 57, 14}, },
            {{61, 61, 49}, },
            {},
            {{61, 61, 50}, {62, 62, 51}, },
            {},
            {{61, 61, 52}, },
            {{48, 57, 53}, {65, 90, 54}, {95, 95, 55}, {97, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {},
            {},
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 115, 56}, {116, 116, 57}, {117, 117, 56}, {118, 118, 58}, {119, 122, 56}, },
            {{48, 95, -22}, {97, 110, 56}, {111, 111, 59}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 97, 60}, {98, 110, 56}, {111, 111, 61}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 100, 56}, {101, 101, 62}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 109, 56}, {110, 110, 63}, {111, 114, 56}, {115, 115, 64}, {116, 122, 56}, },
            {{48, 95, -22}, {97, 97, 65}, {98, 104, 56}, {105, 105, 66}, {106, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 109, -32}, {110, 110, 67}, {111, 122, 56}, },
            {{48, 100, -31}, {101, 101, 68}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 69}, {98, 122, 56}, },
            {{48, 95, -22}, {97, 116, 56}, {117, 117, 70}, {118, 122, 56}, },
            {{48, 95, -22}, {97, 97, 71}, {98, 113, 56}, {114, 114, 72}, {115, 122, 56}, },
            {{48, 100, -31}, {101, 101, 73}, {102, 122, 56}, },
            {{48, 100, -31}, {101, 101, 74}, {102, 122, 56}, },
            {{48, 100, -31}, {101, 101, 75}, {102, 122, 56}, },
            {{9, 32, -2}, },
            {{0, 65535, -7}, },
            {{0, 65535, -7}, },
            {},
            {{44, 44, 48}, {48, 57, 45}, },
            {},
            {{0, 9, 76}, {10, 10, 77}, {11, 12, 76}, {14, 65535, 76}, },
            {{48, 57, 78}, },
            {},
            {},
            {},
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 100, -31}, {101, 101, 79}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 80}, {98, 122, 56}, },
            {{48, 110, -29}, {111, 111, 81}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 113, 56}, {114, 114, 82}, {115, 115, 83}, {116, 122, 56}, },
            {{48, 109, -32}, {110, 110, 84}, {111, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 112, 56}, {113, 113, 85}, {114, 115, 56}, {116, 116, 86}, {117, 122, 56}, },
            {{48, 95, -22}, {97, 98, 56}, {99, 99, 87}, {100, 122, 56}, },
            {{48, 98, -66}, {99, 99, 88}, {100, 107, 56}, {108, 108, 89}, {109, 122, 56}, },
            {{48, 95, -22}, {97, 108, 56}, {109, 109, 90}, {110, 122, 56}, },
            {{48, 95, -22}, {97, 104, 56}, {105, 105, 91}, {106, 115, 56}, {116, 116, 92}, {117, 122, 56}, },
            {{48, 104, -69}, {105, 105, 93}, {106, 122, 56}, },
            {{48, 110, -29}, {111, 111, 94}, {112, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 113, -62}, {114, 114, 95}, {115, 115, 96}, {116, 122, 56}, },
            {{48, 110, -29}, {111, 111, 97}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 97, 98}, {98, 111, 56}, {112, 112, 99}, {113, 122, 56}, },
            {{48, 109, -32}, {110, 110, 100}, {111, 122, 56}, },
            {{48, 113, -62}, {114, 114, 101}, {115, 115, 56}, {116, 116, 102}, {117, 122, 56}, },
            {{0, 65535, -49}, },
            {},
            {{48, 57, 78}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 107, 56}, {108, 108, 103}, {109, 122, 56}, },
            {{48, 107, -82}, {108, 108, 104}, {109, 122, 56}, },
            {{48, 95, -22}, {97, 97, 105}, {98, 122, 56}, },
            {{48, 110, -29}, {111, 111, 106}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 114, 56}, {115, 115, 107}, {116, 122, 56}, },
            {{48, 116, -38}, {117, 117, 108}, {118, 122, 56}, },
            {{48, 95, -22}, {97, 97, 109}, {98, 122, 56}, },
            {{48, 113, -62}, {114, 114, 110}, {115, 122, 56}, },
            {{48, 95, -22}, {97, 97, 111}, {98, 122, 56}, },
            {{48, 114, -86}, {115, 115, 112}, {116, 122, 56}, },
            {{32, 32, 113}, {46, 46, 114}, {48, 122, -22}, },
            {{48, 98, -66}, {99, 99, 115}, {100, 122, 56}, },
            {{48, 100, -31}, {101, 101, 116}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 117}, {98, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 118}, {98, 122, 56}, },
            {{48, 114, -86}, {115, 115, 119}, {116, 122, 56}, },
            {{48, 95, -22}, {97, 102, 56}, {103, 103, 120}, {104, 122, 56}, },
            {{48, 107, -82}, {108, 108, 121}, {109, 122, 56}, },
            {{48, 104, -69}, {105, 105, 122}, {106, 122, 56}, },
            {{48, 95, -22}, {97, 97, 123}, {98, 122, 56}, },
            {{48, 95, -22}, {97, 99, 56}, {100, 100, 124}, {101, 122, 56}, },
            {{48, 110, -29}, {111, 111, 125}, {112, 122, 56}, },
            {{48, 104, -69}, {105, 105, 126}, {106, 122, 56}, },
            {{48, 100, -31}, {101, 101, 127}, {102, 122, 56}, },
            {{48, 98, -66}, {99, 99, 128}, {100, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 115, -28}, {116, 116, 129}, {117, 122, 56}, },
            {{48, 95, -22}, {97, 97, 130}, {98, 122, 56}, },
            {{48, 110, -29}, {111, 111, 131}, {112, 122, 56}, },
            {{48, 100, -31}, {101, 101, 132}, {102, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 110, -29}, {111, 111, 133}, {112, 122, 56}, },
            {{97, 97, 134}, {101, 101, 135}, {112, 112, 136}, {115, 115, 137}, },
            {},
            {{48, 104, -69}, {105, 105, 138}, {106, 122, 56}, },
            {{48, 104, -69}, {105, 105, 139}, {106, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 110, -29}, {111, 111, 140}, {112, 122, 56}, },
            {{48, 113, -62}, {114, 114, 141}, {115, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 115, -28}, {116, 116, 142}, {117, 122, 56}, },
            {{48, 110, -29}, {111, 111, 143}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 97, 144}, {98, 122, 56}, },
            {{48, 113, -62}, {114, 114, 145}, {115, 122, 56}, },
            {{48, 100, -31}, {101, 101, 146}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 147}, {98, 122, 56}, },
            {{48, 115, -28}, {116, 116, 148}, {117, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 109, -32}, {110, 110, 149}, {111, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 117, 56}, {118, 118, 150}, {119, 122, 56}, },
            {{48, 122, -22}, },
            {{118, 118, 151}, },
            {{110, 110, 152}, },
            {{97, 97, 153}, },
            {{101, 101, 154}, },
            {{48, 110, -29}, {111, 111, 155}, {112, 122, 56}, },
            {{48, 113, -62}, {114, 114, 156}, {115, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 157}, {98, 122, 56}, },
            {{48, 95, -22}, {97, 97, 158}, {98, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 99, -103}, {100, 100, 159}, {101, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 109, -32}, {110, 110, 160}, {111, 122, 56}, },
            {{48, 100, -31}, {101, 101, 161}, {102, 122, 56}, },
            {{48, 115, -28}, {116, 116, 162}, {117, 122, 56}, },
            {{48, 95, -22}, {97, 97, 163}, {98, 122, 56}, },
            {{97, 97, 164}, },
            {{113, 113, 165}, },
            {{114, 114, 166}, },
            {},
            {{48, 122, -22}, },
            {{48, 110, -29}, {111, 111, 167}, {112, 122, 56}, },
            {{48, 108, -68}, {109, 109, 168}, {110, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 100, -31}, {101, 101, 169}, {102, 122, 56}, },
            {{48, 110, -29}, {111, 111, 170}, {112, 122, 56}, },
            {{48, 113, -62}, {114, 114, 171}, {115, 122, 56}, },
            {{48, 110, -29}, {111, 111, 172}, {112, 122, 56}, },
            {{48, 122, -22}, },
            {{108, 108, 173}, },
            {{117, 117, 174}, },
            {{97, 97, 175}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 176}, {98, 122, 56}, },
            {{48, 104, -69}, {105, 105, 177}, {106, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 100, -31}, {101, 101, 178}, {102, 122, 56}, },
            {{48, 122, -22}, },
            {{105, 105, 179}, },
            {{97, 97, 180}, },
            {},
            {{48, 122, -22}, },
            {{48, 113, -62}, {114, 114, 181}, {115, 122, 56}, },
            {{48, 122, -22}, },
            {{101, 101, 182}, },
            {{110, 110, 183}, },
            {{48, 110, -29}, {111, 111, 184}, {112, 122, 56}, },
            {},
            {{116, 116, 185}, },
            {{48, 122, -22}, },
            {{111, 111, 186}, },
            {},
        }
        { // COMENTARIO
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {39, 39, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {65, 79, 20}, {80, 80, 21}, {81, 83, 20}, {84, 84, 22}, {85, 90, 20}, {91, 91, 23}, {93, 93, 24}, {95, 95, 25}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 32}, {105, 105, 33}, {106, 107, 32}, {108, 108, 34}, {109, 109, 32}, {110, 110, 35}, {111, 111, 36}, {112, 112, 37}, {113, 113, 32}, {114, 114, 38}, {115, 115, 39}, {116, 117, 32}, {118, 118, 40}, {119, 122, 32}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 41}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 9, 42}, {11, 12, 42}, {14, 38, 42}, {39, 39, 43}, {40, 65535, 42}, },
            {},
            {},
            {{47, 47, 44}, },
            {},
            {},
            {{48, 57, 45}, },
            {},
            {{42, 42, 46}, {47, 47, 47}, },
            {{44, 44, 48}, {48, 57, 14}, },
            {{61, 61, 49}, },
            {},
            {{61, 61, 50}, {62, 62, 51}, },
            {},
            {{61, 61, 52}, },
            {{48, 57, 53}, {65, 90, 54}, {95, 95, 55}, {97, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {},
            {},
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 115, 56}, {116, 116, 57}, {117, 117, 56}, {118, 118, 58}, {119, 122, 56}, },
            {{48, 95, -22}, {97, 110, 56}, {111, 111, 59}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 97, 60}, {98, 110, 56}, {111, 111, 61}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 100, 56}, {101, 101, 62}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 109, 56}, {110, 110, 63}, {111, 114, 56}, {115, 115, 64}, {116, 122, 56}, },
            {{48, 95, -22}, {97, 97, 65}, {98, 104, 56}, {105, 105, 66}, {106, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 109, -32}, {110, 110, 67}, {111, 122, 56}, },
            {{48, 100, -31}, {101, 101, 68}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 69}, {98, 122, 56}, },
            {{48, 95, -22}, {97, 116, 56}, {117, 117, 70}, {118, 122, 56}, },
            {{48, 95, -22}, {97, 97, 71}, {98, 113, 56}, {114, 114, 72}, {115, 122, 56}, },
            {{48, 100, -31}, {101, 101, 73}, {102, 122, 56}, },
            {{48, 100, -31}, {101, 101, 74}, {102, 122, 56}, },
            {{48, 100, -31}, {101, 101, 75}, {102, 122, 56}, },
            {{9, 32, -2}, },
            {{0, 65535, -7}, },
            {{0, 65535, -7}, },
            {},
            {{44, 44, 48}, {48, 57, 45}, },
            {},
            {{0, 9, 76}, {10, 10, 77}, {11, 12, 76}, {14, 65535, 76}, },
            {{48, 57, 78}, },
            {},
            {},
            {},
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 100, -31}, {101, 101, 79}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 80}, {98, 122, 56}, },
            {{48, 110, -29}, {111, 111, 81}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 113, 56}, {114, 114, 82}, {115, 115, 83}, {116, 122, 56}, },
            {{48, 109, -32}, {110, 110, 84}, {111, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 112, 56}, {113, 113, 85}, {114, 115, 56}, {116, 116, 86}, {117, 122, 56}, },
            {{48, 95, -22}, {97, 98, 56}, {99, 99, 87}, {100, 122, 56}, },
            {{48, 98, -66}, {99, 99, 88}, {100, 107, 56}, {108, 108, 89}, {109, 122, 56}, },
            {{48, 95, -22}, {97, 108, 56}, {109, 109, 90}, {110, 122, 56}, },
            {{48, 95, -22}, {97, 104, 56}, {105, 105, 91}, {106, 115, 56}, {116, 116, 92}, {117, 122, 56}, },
            {{48, 104, -69}, {105, 105, 93}, {106, 122, 56}, },
            {{48, 110, -29}, {111, 111, 94}, {112, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 113, -62}, {114, 114, 95}, {115, 115, 96}, {116, 122, 56}, },
            {{48, 110, -29}, {111, 111, 97}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 97, 98}, {98, 111, 56}, {112, 112, 99}, {113, 122, 56}, },
            {{48, 109, -32}, {110, 110, 100}, {111, 122, 56}, },
            {{48, 113, -62}, {114, 114, 101}, {115, 115, 56}, {116, 116, 102}, {117, 122, 56}, },
            {{0, 65535, -49}, },
            {},
            {{48, 57, 78}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 107, 56}, {108, 108, 103}, {109, 122, 56}, },
            {{48, 107, -82}, {108, 108, 104}, {109, 122, 56}, },
            {{48, 95, -22}, {97, 97, 105}, {98, 122, 56}, },
            {{48, 110, -29}, {111, 111, 106}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 114, 56}, {115, 115, 107}, {116, 122, 56}, },
            {{48, 116, -38}, {117, 117, 108}, {118, 122, 56}, },
            {{48, 95, -22}, {97, 97, 109}, {98, 122, 56}, },
            {{48, 113, -62}, {114, 114, 110}, {115, 122, 56}, },
            {{48, 95, -22}, {97, 97, 111}, {98, 122, 56}, },
            {{48, 114, -86}, {115, 115, 112}, {116, 122, 56}, },
            {{32, 32, 113}, {46, 46, 114}, {48, 122, -22}, },
            {{48, 98, -66}, {99, 99, 115}, {100, 122, 56}, },
            {{48, 100, -31}, {101, 101, 116}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 117}, {98, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 118}, {98, 122, 56}, },
            {{48, 114, -86}, {115, 115, 119}, {116, 122, 56}, },
            {{48, 95, -22}, {97, 102, 56}, {103, 103, 120}, {104, 122, 56}, },
            {{48, 107, -82}, {108, 108, 121}, {109, 122, 56}, },
            {{48, 104, -69}, {105, 105, 122}, {106, 122, 56}, },
            {{48, 95, -22}, {97, 97, 123}, {98, 122, 56}, },
            {{48, 95, -22}, {97, 99, 56}, {100, 100, 124}, {101, 122, 56}, },
            {{48, 110, -29}, {111, 111, 125}, {112, 122, 56}, },
            {{48, 104, -69}, {105, 105, 126}, {106, 122, 56}, },
            {{48, 100, -31}, {101, 101, 127}, {102, 122, 56}, },
            {{48, 98, -66}, {99, 99, 128}, {100, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 115, -28}, {116, 116, 129}, {117, 122, 56}, },
            {{48, 95, -22}, {97, 97, 130}, {98, 122, 56}, },
            {{48, 110, -29}, {111, 111, 131}, {112, 122, 56}, },
            {{48, 100, -31}, {101, 101, 132}, {102, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 110, -29}, {111, 111, 133}, {112, 122, 56}, },
            {{97, 97, 134}, {101, 101, 135}, {112, 112, 136}, {115, 115, 137}, },
            {},
            {{48, 104, -69}, {105, 105, 138}, {106, 122, 56}, },
            {{48, 104, -69}, {105, 105, 139}, {106, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 110, -29}, {111, 111, 140}, {112, 122, 56}, },
            {{48, 113, -62}, {114, 114, 141}, {115, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 115, -28}, {116, 116, 142}, {117, 122, 56}, },
            {{48, 110, -29}, {111, 111, 143}, {112, 122, 56}, },
            {{48, 95, -22}, {97, 97, 144}, {98, 122, 56}, },
            {{48, 113, -62}, {114, 114, 145}, {115, 122, 56}, },
            {{48, 100, -31}, {101, 101, 146}, {102, 122, 56}, },
            {{48, 95, -22}, {97, 97, 147}, {98, 122, 56}, },
            {{48, 115, -28}, {116, 116, 148}, {117, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 109, -32}, {110, 110, 149}, {111, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 117, 56}, {118, 118, 150}, {119, 122, 56}, },
            {{48, 122, -22}, },
            {{118, 118, 151}, },
            {{110, 110, 152}, },
            {{97, 97, 153}, },
            {{101, 101, 154}, },
            {{48, 110, -29}, {111, 111, 155}, {112, 122, 56}, },
            {{48, 113, -62}, {114, 114, 156}, {115, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 157}, {98, 122, 56}, },
            {{48, 95, -22}, {97, 97, 158}, {98, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 99, -103}, {100, 100, 159}, {101, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 109, -32}, {110, 110, 160}, {111, 122, 56}, },
            {{48, 100, -31}, {101, 101, 161}, {102, 122, 56}, },
            {{48, 115, -28}, {116, 116, 162}, {117, 122, 56}, },
            {{48, 95, -22}, {97, 97, 163}, {98, 122, 56}, },
            {{97, 97, 164}, },
            {{113, 113, 165}, },
            {{114, 114, 166}, },
            {},
            {{48, 122, -22}, },
            {{48, 110, -29}, {111, 111, 167}, {112, 122, 56}, },
            {{48, 108, -68}, {109, 109, 168}, {110, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 100, -31}, {101, 101, 169}, {102, 122, 56}, },
            {{48, 110, -29}, {111, 111, 170}, {112, 122, 56}, },
            {{48, 113, -62}, {114, 114, 171}, {115, 122, 56}, },
            {{48, 110, -29}, {111, 111, 172}, {112, 122, 56}, },
            {{48, 122, -22}, },
            {{108, 108, 173}, },
            {{117, 117, 174}, },
            {{97, 97, 175}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 97, 176}, {98, 122, 56}, },
            {{48, 104, -69}, {105, 105, 177}, {106, 122, 56}, },
            {{48, 122, -22}, },
            {{48, 100, -31}, {101, 101, 178}, {102, 122, 56}, },
            {{48, 122, -22}, },
            {{105, 105, 179}, },
            {{97, 97, 180}, },
            {},
            {{48, 122, -22}, },
            {{48, 113, -62}, {114, 114, 181}, {115, 122, 56}, },
            {{48, 122, -22}, },
            {{101, 101, 182}, },
            {{110, 110, 183}, },
            {{48, 110, -29}, {111, 111, 184}, {112, 122, 56}, },
            {},
            {{116, 116, 185}, },
            {{48, 122, -22}, },
            {{111, 111, 186}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 61, 61, 61, 61, -1, 45, 46, 33, 31, 49, 32, 51, 34, 57, 52, 50, 36, 39, 35, 56, 30, 29, 47, 48, 56, 56, 56, 56, 56, 42, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 61, -1, 60, 55, 58, 54, -1, -1, 44, 38, 40, 37, 56, 56, 56, 56, 56, 56, 56, 56, 56, 18, 56, 56, 56, 56, 56, 56, 56, 43, 56, 56, 56, 6, 56, -1, 53, 59, 20, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 41, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 11, 56, 56, 56, 56, 14, 56, -1, 5, 56, 56, 25, 17, 56, 56, 2, 56, 56, 56, 56, 56, 56, 56, 28, 56, 7, 56, 23, -1, -1, -1, -1, 56, 56, 19, 56, 56, 8, 56, 27, 10, 56, 56, 56, 56, -1, -1, -1, 9, 4, 56, 56, 16, 56, 56, 56, 56, 26, -1, -1, -1, 1, 56, 56, 3, 56, 13, -1, -1, 21, 24, 56, 0, -1, -1, 56, 12, -1, 22, -1, 15, },
        // COMENTARIO
        {-1, 61, 61, 61, 61, -1, 45, 46, 33, 31, 49, 32, 51, 34, 57, 52, 50, 36, 39, 35, 56, 30, 29, 47, 48, 56, 56, 56, 56, 56, 42, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 61, -1, 60, 55, 58, 54, -1, -1, 44, 38, 40, 37, 56, 56, 56, 56, 56, 56, 56, 56, 56, 18, 56, 56, 56, 56, 56, 56, 56, 43, 56, 56, 56, 6, 56, -1, 53, 59, 20, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 41, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 11, 56, 56, 56, 56, 14, 56, -1, 5, 56, 56, 25, 17, 56, 56, 2, 56, 56, 56, 56, 56, 56, 56, 28, 56, 7, 56, 23, -1, -1, -1, -1, 56, 56, 19, 56, 56, 8, 56, 27, 10, 56, 56, 56, 56, -1, -1, -1, 9, 4, 56, 56, 16, 56, 56, 56, 56, 26, -1, -1, -1, 1, 56, 56, 3, 56, 13, -1, -1, 21, 24, 56, 0, -1, -1, 56, 12, -1, 22, -1, 15, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
