/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAtribuicaoComando extends PComando
{
    private PComandoAtribuicao _comandoAtribuicao_;

    public AAtribuicaoComando()
    {
        // Constructor
    }

    public AAtribuicaoComando(
        @SuppressWarnings("hiding") PComandoAtribuicao _comandoAtribuicao_)
    {
        // Constructor
        setComandoAtribuicao(_comandoAtribuicao_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuicaoComando(
            cloneNode(this._comandoAtribuicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuicaoComando(this);
    }

    public PComandoAtribuicao getComandoAtribuicao()
    {
        return this._comandoAtribuicao_;
    }

    public void setComandoAtribuicao(PComandoAtribuicao node)
    {
        if(this._comandoAtribuicao_ != null)
        {
            this._comandoAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAtribuicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoAtribuicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoAtribuicao_ == child)
        {
            this._comandoAtribuicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoAtribuicao_ == oldChild)
        {
            setComandoAtribuicao((PComandoAtribuicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
