/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEscritaComando extends PComando
{
    private PComandoEscrita _comandoEscrita_;

    public AEscritaComando()
    {
        // Constructor
    }

    public AEscritaComando(
        @SuppressWarnings("hiding") PComandoEscrita _comandoEscrita_)
    {
        // Constructor
        setComandoEscrita(_comandoEscrita_);

    }

    @Override
    public Object clone()
    {
        return new AEscritaComando(
            cloneNode(this._comandoEscrita_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEscritaComando(this);
    }

    public PComandoEscrita getComandoEscrita()
    {
        return this._comandoEscrita_;
    }

    public void setComandoEscrita(PComandoEscrita node)
    {
        if(this._comandoEscrita_ != null)
        {
            this._comandoEscrita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoEscrita_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoEscrita_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoEscrita_ == child)
        {
            this._comandoEscrita_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoEscrita_ == oldChild)
        {
            setComandoEscrita((PComandoEscrita) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
