/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMaiorOperacaologica extends POperacaologica
{
    private TMaiorq _maiorq_;

    public AMaiorOperacaologica()
    {
        // Constructor
    }

    public AMaiorOperacaologica(
        @SuppressWarnings("hiding") TMaiorq _maiorq_)
    {
        // Constructor
        setMaiorq(_maiorq_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorOperacaologica(
            cloneNode(this._maiorq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorOperacaologica(this);
    }

    public TMaiorq getMaiorq()
    {
        return this._maiorq_;
    }

    public void setMaiorq(TMaiorq node)
    {
        if(this._maiorq_ != null)
        {
            this._maiorq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorq_ == child)
        {
            this._maiorq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorq_ == oldChild)
        {
            setMaiorq((TMaiorq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
