/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMaiorOperacaologica extends POperacaologica
{
    private TMaiorque _maiorque_;

    public AMaiorOperacaologica()
    {
        // Constructor
    }

    public AMaiorOperacaologica(
        @SuppressWarnings("hiding") TMaiorque _maiorque_)
    {
        // Constructor
        setMaiorque(_maiorque_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorOperacaologica(
            cloneNode(this._maiorque_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorOperacaologica(this);
    }

    public TMaiorque getMaiorque()
    {
        return this._maiorque_;
    }

    public void setMaiorque(TMaiorque node)
    {
        if(this._maiorque_ != null)
        {
            this._maiorque_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorque_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorque_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorque_ == child)
        {
            this._maiorque_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorque_ == oldChild)
        {
            setMaiorque((TMaiorque) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
