/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMenorOperacaologica extends POperacaologica
{
    private TMenorque _menorque_;

    public AMenorOperacaologica()
    {
        // Constructor
    }

    public AMenorOperacaologica(
        @SuppressWarnings("hiding") TMenorque _menorque_)
    {
        // Constructor
        setMenorque(_menorque_);

    }

    @Override
    public Object clone()
    {
        return new AMenorOperacaologica(
            cloneNode(this._menorque_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorOperacaologica(this);
    }

    public TMenorque getMenorque()
    {
        return this._menorque_;
    }

    public void setMenorque(TMenorque node)
    {
        if(this._menorque_ != null)
        {
            this._menorque_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorque_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menorque_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menorque_ == child)
        {
            this._menorque_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menorque_ == oldChild)
        {
            setMenorque((TMenorque) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
