/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOperacaologicaExpr extends PExpr
{
    private PExpr _primeiro_;
    private POperacaologica _operacaologica_;
    private PExpr _segundo_;

    public AOperacaologicaExpr()
    {
        // Constructor
    }

    public AOperacaologicaExpr(
        @SuppressWarnings("hiding") PExpr _primeiro_,
        @SuppressWarnings("hiding") POperacaologica _operacaologica_,
        @SuppressWarnings("hiding") PExpr _segundo_)
    {
        // Constructor
        setPrimeiro(_primeiro_);

        setOperacaologica(_operacaologica_);

        setSegundo(_segundo_);

    }

    @Override
    public Object clone()
    {
        return new AOperacaologicaExpr(
            cloneNode(this._primeiro_),
            cloneNode(this._operacaologica_),
            cloneNode(this._segundo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOperacaologicaExpr(this);
    }

    public PExpr getPrimeiro()
    {
        return this._primeiro_;
    }

    public void setPrimeiro(PExpr node)
    {
        if(this._primeiro_ != null)
        {
            this._primeiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primeiro_ = node;
    }

    public POperacaologica getOperacaologica()
    {
        return this._operacaologica_;
    }

    public void setOperacaologica(POperacaologica node)
    {
        if(this._operacaologica_ != null)
        {
            this._operacaologica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacaologica_ = node;
    }

    public PExpr getSegundo()
    {
        return this._segundo_;
    }

    public void setSegundo(PExpr node)
    {
        if(this._segundo_ != null)
        {
            this._segundo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._segundo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primeiro_)
            + toString(this._operacaologica_)
            + toString(this._segundo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primeiro_ == child)
        {
            this._primeiro_ = null;
            return;
        }

        if(this._operacaologica_ == child)
        {
            this._operacaologica_ = null;
            return;
        }

        if(this._segundo_ == child)
        {
            this._segundo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primeiro_ == oldChild)
        {
            setPrimeiro((PExpr) newChild);
            return;
        }

        if(this._operacaologica_ == oldChild)
        {
            setOperacaologica((POperacaologica) newChild);
            return;
        }

        if(this._segundo_ == oldChild)
        {
            setSegundo((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
