/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOperacaoExpr extends PExpr
{
    private PExpr _primeiro_;
    private POperacao _operacao_;
    private PExpr _segundo_;

    public AOperacaoExpr()
    {
        // Constructor
    }

    public AOperacaoExpr(
        @SuppressWarnings("hiding") PExpr _primeiro_,
        @SuppressWarnings("hiding") POperacao _operacao_,
        @SuppressWarnings("hiding") PExpr _segundo_)
    {
        // Constructor
        setPrimeiro(_primeiro_);

        setOperacao(_operacao_);

        setSegundo(_segundo_);

    }

    @Override
    public Object clone()
    {
        return new AOperacaoExpr(
            cloneNode(this._primeiro_),
            cloneNode(this._operacao_),
            cloneNode(this._segundo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOperacaoExpr(this);
    }

    public PExpr getPrimeiro()
    {
        return this._primeiro_;
    }

    public void setPrimeiro(PExpr node)
    {
        if(this._primeiro_ != null)
        {
            this._primeiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primeiro_ = node;
    }

    public POperacao getOperacao()
    {
        return this._operacao_;
    }

    public void setOperacao(POperacao node)
    {
        if(this._operacao_ != null)
        {
            this._operacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacao_ = node;
    }

    public PExpr getSegundo()
    {
        return this._segundo_;
    }

    public void setSegundo(PExpr node)
    {
        if(this._segundo_ != null)
        {
            this._segundo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._segundo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primeiro_)
            + toString(this._operacao_)
            + toString(this._segundo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primeiro_ == child)
        {
            this._primeiro_ = null;
            return;
        }

        if(this._operacao_ == child)
        {
            this._operacao_ = null;
            return;
        }

        if(this._segundo_ == child)
        {
            this._segundo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primeiro_ == oldChild)
        {
            setPrimeiro((PExpr) newChild);
            return;
        }

        if(this._operacao_ == oldChild)
        {
            setOperacao((POperacao) newChild);
            return;
        }

        if(this._segundo_ == oldChild)
        {
            setSegundo((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
