/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ARepitaComando extends PComando
{
    private PComandoRepita _comandoRepita_;

    public ARepitaComando()
    {
        // Constructor
    }

    public ARepitaComando(
        @SuppressWarnings("hiding") PComandoRepita _comandoRepita_)
    {
        // Constructor
        setComandoRepita(_comandoRepita_);

    }

    @Override
    public Object clone()
    {
        return new ARepitaComando(
            cloneNode(this._comandoRepita_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepitaComando(this);
    }

    public PComandoRepita getComandoRepita()
    {
        return this._comandoRepita_;
    }

    public void setComandoRepita(PComandoRepita node)
    {
        if(this._comandoRepita_ != null)
        {
            this._comandoRepita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoRepita_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoRepita_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoRepita_ == child)
        {
            this._comandoRepita_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoRepita_ == oldChild)
        {
            setComandoRepita((PComandoRepita) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
