/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ASempassoComandoPara extends PComandoPara
{
    private PVar _var_;
    private PParatipos _paratipos_;
    private PParatipos _segundo_;
    private final LinkedList<PComando> _comando_ = new LinkedList<PComando>();

    public ASempassoComandoPara()
    {
        // Constructor
    }

    public ASempassoComandoPara(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") PParatipos _paratipos_,
        @SuppressWarnings("hiding") PParatipos _segundo_,
        @SuppressWarnings("hiding") List<?> _comando_)
    {
        // Constructor
        setVar(_var_);

        setParatipos(_paratipos_);

        setSegundo(_segundo_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new ASempassoComandoPara(
            cloneNode(this._var_),
            cloneNode(this._paratipos_),
            cloneNode(this._segundo_),
            cloneList(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASempassoComandoPara(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PParatipos getParatipos()
    {
        return this._paratipos_;
    }

    public void setParatipos(PParatipos node)
    {
        if(this._paratipos_ != null)
        {
            this._paratipos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paratipos_ = node;
    }

    public PParatipos getSegundo()
    {
        return this._segundo_;
    }

    public void setSegundo(PParatipos node)
    {
        if(this._segundo_ != null)
        {
            this._segundo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._segundo_ = node;
    }

    public LinkedList<PComando> getComando()
    {
        return this._comando_;
    }

    public void setComando(List<?> list)
    {
        for(PComando e : this._comando_)
        {
            e.parent(null);
        }
        this._comando_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comando_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._paratipos_)
            + toString(this._segundo_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._paratipos_ == child)
        {
            this._paratipos_ = null;
            return;
        }

        if(this._segundo_ == child)
        {
            this._segundo_ = null;
            return;
        }

        if(this._comando_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._paratipos_ == oldChild)
        {
            setParatipos((PParatipos) newChild);
            return;
        }

        if(this._segundo_ == oldChild)
        {
            setSegundo((PParatipos) newChild);
            return;
        }

        for(ListIterator<PComando> i = this._comando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
